# Generated by Django 5.1.5 on 2025-03-04 13:54

import library_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_book_genre_book_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='due_date',
            field=models.DateTimeField(default=library_app.models.default_due_date),
        ),
        migrations.AddField(
            model_name='borrow',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
