# Generated by Django 5.1.5 on 2025-03-06 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_borrow_due_date_borrow_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='return_date',
        ),
        migrations.AddField(
            model_name='borrow',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
