# Generated by Django 5.1.5 on 2025-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_author_remove_post_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
